name: Auto Release Zip

on:
  push:
    branches: ["main"]

jobs:
  build_and_publish:
    runs-on: codeberg-small

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine next version
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git tag -l "V*" | sort -V | tail -n1)
          if [ -z "$LAST_TAG" ]; then
            NEXT_VERSION=1
          else
            NUM=${LAST_TAG#V}
            NEXT_VERSION=$((NUM + 1))
          fi
          echo "Next version: $NEXT_VERSION"
          echo "RELEASE_TAG=V$NEXT_VERSION" >> $GITHUB_ENV
          echo "ZIP_FILE=the-fun-guns-V$NEXT_VERSION.zip" >> $GITHUB_ENV

      - name: Create ZIP artifact (excluding unwanted files)
        run: |
          zip -r "${ZIP_FILE}" . \
            -x "*.md" \
            -x "LICENSE" \
            -x "*.db" \
            -x ".vs/*" \
            -x ".gitignore" \
            -x ".git/*" \
            -x ".yaml"

      - name: Create Git tag
        run: |
          git tag "$RELEASE_TAG"
          git push origin "$RELEASE_TAG"

      - name: Create Codeberg release via API
        run: |
          curl -s -X POST "https://codeberg.org/api/v1/repos/TheBLABS/The-Fun-Guns/releases" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.CODEBERG_TOKEN }}" \
            -d "{\"tag_name\":\"${RELEASE_TAG}\",\"name\":\"The Fun Guns ${RELEASE_TAG}\"}"

      - name: Upload release asset
        run: |
          RELEASE_ID=$(curl -s "https://codeberg.org/api/v1/repos/TheBLABS/The-Fun-Guns/releases/tags/${RELEASE_TAG}" \
            -H "Authorization: token ${{ secrets.CODEBERG_TOKEN }}" | jq -r ".id")
          curl -X POST "https://codeberg.org/api/v1/repos/TheBLABS/The-Fun-Guns/releases/$RELEASE_ID/assets?name=${ZIP_FILE}" \
            -H "Authorization: token ${{ secrets.CODEBERG_TOKEN }}" \
            --data-binary @"${ZIP_FILE}"
